openapi: 3.0.0
info:
  title: AI Backend
  version: 0.1.0
paths:
  /:
    summary: Say Hello
    get:
      summary: sayHello
      operationId: SayHello
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema: {}
  /ask:
    summary: Ask Question
    post:
      summary: askQuestion
      operationId: AskQuestion
      requestBody:
        content:
          application/json:
            schema: {
              "$ref": "#/components/schemas/Query"
            }
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"


components:
  schemas:
    Response:
      type: object
      properties:
        resp:
          type: string
    Query:
      type: object
      properties:
        message:
          type: string
